name: Build and Security Scan

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Application
      run: |
        mkdir dist
        echo "My App Content" > dist/my-application.exe

    - name: VirusTotal Scan
      id: vt
      uses: cssnr/virustotal-action@v1.1.0
      with:
        files: |
          dist/my-application.exe
        vt-api-key: ${{ secrets.VIRUSTOTAL_API_KEY }}

    - name: Show VirusTotal Link
      run: |
        echo "Your VirusTotal scan results are available here:"
        echo "${{ steps.vt.outputs.analysis-url }}"
